### PR TITLE
Add a property to the Tasklist widget to disable automatic switching between buttons using the scroll wheel.

### PR DESCRIPTION
**Pull request by jsgh**
(Requires a corresponding change in mate-panel to be useful...)

### CODE REVIEW

**Comment by infirit** [comment]
Thanks but.. we don't use libmatewnck any-more. We switched back to libwnck. You can open a PR on https://github.com/gnome/libwnck to get this implemented. Be sure to ask for it to be in both gtk2 and gtk3 wnck versions.

**Comment by jsgh** [comment]
Gah! They'd never accept it.

It's necessary to support https://github.com/mate-desktop/mate-panel/pull/223 - I was hoping to be rid of the local patch I've been maintaining for the last 4 years (which is, by the way, a much older feature request that used to get made frequently against Gnome 2 and was always ignored...)

**Comment by stefano-k** [comment]
> Gah! They'd never accept it.

@jsgh this is not true

**Comment by stefano-k** [comment]
However, closing this PR here because libmatewnck is no more developed and used

**Pull request closed without merging**
